# Generated by Django 4.2.23 on 2025-09-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
