"""
Django settings for journal project.
Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
from decouple import config
import os

# =========================
# 📂 Chemins de base
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# 🔑 Sécurité & configuration
# =========================
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-@jqdjx99c+^@wl@hqfga=vzcufq^dw8#61i48y2&5il-9uf6+y"
)
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)
ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="baoulynelson.pythonanywhere.com"
).split(",")


# =========================
# 📦 Applications
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "articles.apps.ArticlesConfig",  # pas juste "articles"
    "widget_tweaks",
    "django.contrib.humanize",
    "channels",
]

# =========================
# ⚙️ Middleware
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# =========================
# 🌐 Routage
# =========================
ROOT_URLCONF = "journal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "articles" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "articles.context_processors.dashboard_stats",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "journal.wsgi.application"
ASGI_APPLICATION = "journal.asgi.application"

# Channels (en mémoire en dev — utiliser Redis en prod)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

# =========================
# 🗄️ Base de données (MySQL)
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="127.0.0.1"),
        "PORT": config("DB_PORT", default="3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "use_unicode": True,
            "init_command": (
                "SET sql_mode='STRICT_TRANS_TABLES', "
                "NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';"
            ),
        },
    }
}

# =========================
# 📧 Email
# =========================
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

ADMIN_EMAIL = config("ADMIN_EMAIL")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =========================
# 🔒 Authentification
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LOGIN_REDIRECT_URL = "articles:index"
LOGOUT_REDIRECT_URL = "articles:index"

# =========================
# 🌍 Internationalisation
# =========================
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================
# 🖼️ Fichiers statiques & médias
# =========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # utilisé par collectstatic (prod)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =========================
# ⚙️ Configuration par défaut
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
